### ISSUE TITLE
no items, Background.Backpack this.providers empty

### ISSUE THREAD

**Issue by wolfspelz** [lupuslabs/n3qExt#149]

**Comment by AllanWegan** [comment]
Probably fixed in 8e11c2ec9a63dbbd7f2ef09c0408b392447566d7 by fixing heartbeat handlers being called before a communicator was signaled to do so by calling its start method (missing check).
It was a race between first heartbeat and user ID initialization leading to provider construction failing with an exception after the config JSON had been stored in the cache.
Also hardened the provider handling in backpack maintenance code and made sure that config JSON is only cached if provider initialization doesn't throw in 9c42d300c9a29bfc6926f2652df23c905ede6852.
